version: '3.9'
services:
  web:
    build: .
    command: gunicorn worldwild_backend.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.staging
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    env_file:
      - ./.env.staging
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
