services:
  web:
    build: .  # ruta al Dockerfile
    command: python manage.py runserver 0.0.0.0:8000 --settings=worldwild_backend.settings.local
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.local
    depends_on:
      - db
    environment:
    - DJANGO_SETTINGS_MODULE=worldwild_backend.settings.local
    #environment:
#      POSTGRES_DB: ${POSTGRES_DB}
 #     POSTGRES_USER: ${POSTGRES_USER}
 #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
 #     POSTGRES_HOST: db
 #     POSTGRES_PORT: 5432


  db:
    image: postgres:14
    env_file:
      - ./.env.local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data:
