# Generated by Django 4.2.20 on 2025-06-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateplaninvitation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Invitado'), (1, 'Aceptado'), (2, 'Pagado')], default=0),
        ),
    ]
