# Generated by Django 4.2.20 on 2025-06-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_privateplaninvitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateplan',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='planes_invitados', through='api.PrivatePlanInvitation', to='api.userprofile'),
        ),
    ]
