# Generated by Django 4.2.23 on 2025-09-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_place_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateplan',
            name='invited_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='planes_invitados', through='api.PrivatePlanInvitation', to='api.userprofile'),
        ),
    ]
