# Generated by Django 4.2.20 on 2025-06-20 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_privateplan_invited_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('neededAmount', models.FloatField(default=0.0)),
                ('assignedAmount', models.FloatField(default=0.0)),
                ('people_in_charge', models.ManyToManyField(related_name='items_in_charge', to='api.userprofile')),
                ('private_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.privateplan')),
            ],
        ),
    ]
