# Generated by Django 4.2.23 on 2025-09-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_payment_delete_paymentforuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='available_planes_gratis',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
