# Generated by Django 4.2.20 on 2025-06-20 21:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_itemplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemplan',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
