# Generated by Django 4.2.20 on 2025-06-20 22:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_itemplan_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemplan',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
