# Generated by Django 4.2.23 on 2025-09-22 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userprofile_available_planes_gratis'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('userProfile', models.ManyToManyField(related_name='messages', to='api.userprofile')),
            ],
        ),
    ]
