# Generated by Django 4.2.23 on 2025-09-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_messagetouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetouser',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
