# Generated by Django 5.2.4 on 2025-07-11 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_itemplan_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradasForPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('maxima_disponibilidad', models.FloatField(default=0.0)),
                ('disponibles', models.FloatField(default=0.0)),
                ('precio', models.FloatField(default=0.0)),
                ('titulo', models.TextField()),
                ('desc', models.TextField(blank=True)),
                ('private_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_for_plan', to='api.privateplan')),
            ],
        ),
    ]
