# Generated by Django 5.2.4 on 2025-07-11 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_entradasforplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradasforplan',
            name='private_plan',
        ),
        migrations.AddField(
            model_name='entradasforplan',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_for_plan', to='api.activity'),
        ),
    ]
