# Generated by Django 5.2.4 on 2025-07-11 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_entradasforplan_private_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasforplan',
            name='disponibles',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='entradasforplan',
            name='maxima_disponibilidad',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
