# Generated by Django 4.2.23 on 2025-09-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_amount_payment_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='external_reference',
        ),
    ]
