# Generated by Django 4.2.23 on 2025-09-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_payment_external_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='userProfile',
        ),
        migrations.AddField(
            model_name='payment',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
