# Generated by Django 5.2.4 on 2025-07-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
