# Generated by Django 4.2.23 on 2025-09-29 16:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_description_payment_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='platform_fee',
            field=models.DecimalField(decimal_places=1, default=Decimal('12.5'), max_digits=3),
        ),
    ]
