# Generated by Django 5.2.4 on 2025-07-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_ticket_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[(0, 'No asistido'), (1, 'Asistido')], default=0, max_length=20),
        ),
    ]
