# Generated by Django 4.2.23 on 2025-09-29 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprofile_platform_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to='api.userprofile'),
        ),
    ]
