# Generated by Django 4.2.23 on 2025-09-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_activity_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
