# Generated by Django 5.2.4 on 2025-07-16 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_ticket_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='precio',
        ),
        migrations.AddField(
            model_name='ticket',
            name='entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.entradasforplan'),
        ),
    ]
