# Generated by Django 4.2.23 on 2025-09-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_payment_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='asistentes',
        ),
    ]
