# Generated by Django 4.2.23 on 2025-10-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_promo_asistentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, related_name='activities_collaborated', to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='promo',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, related_name='promos_collaborated', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='profiles_images/'),
        ),
    ]
