# Generated by Django 5.2.4 on 2025-07-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_ticket_content_type_remove_ticket_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privateplan',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
