# Generated by Django 5.2.4 on 2025-07-29 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_activity_direccion_privateplan_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradasforplan',
            name='privateplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_for_plan_privado', to='api.privateplan'),
        ),
        migrations.AddField(
            model_name='entradasforplan',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_for_promo', to='api.promo'),
        ),
    ]
