# Generated by Django 4.2.23 on 2025-10-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_activity_colaboradores_promo_colaboradores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='profiles_images/'),
        ),
    ]
