# Generated by Django 4.2.23 on 2025-10-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='activities_images/'),
        ),
        migrations.AlterField(
            model_name='privateplan',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='private_plans_images/'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='promo_images/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='qr_codes/'),
        ),
    ]
