# Generated by Django 5.2.4 on 2025-08-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_entradasforplan_privateplan_entradasforplan_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='precio',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
