# Generated by Django 5.2.4 on 2025-08-04 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_ticket_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('email', 'Email'), ('number', 'Número'), ('select', 'Seleccionable'), ('date', 'Fecha')], max_length=20)),
                ('requerido', models.BooleanField(default=False)),
                ('opciones', models.JSONField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('userProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_reserva', to='api.userprofile')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('userProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
