# Generated by Django 4.2.23 on 2025-10-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_activity_image_alter_privateplan_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
