# Generated by Django 5.2.4 on 2025-08-04 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_camporeserva_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camporeserva',
            name='userProfile',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='userProfile',
        ),
        migrations.AddField(
            model_name='camporeserva',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campos_reserva', to='api.activity'),
        ),
        migrations.AddField(
            model_name='camporeserva',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campos_reserva', to='api.promo'),
        ),
        migrations.AddField(
            model_name='camporeserva',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='promo',
            name='reserva_necesaria',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='api.activity'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='api.promo'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='activity',
            name='reserva_necesaria',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
