# Generated by Django 4.2.23 on 2025-10-16 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_userprofile_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
    ]
