# Generated by Django 4.2.23 on 2025-10-16 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0020_alter_activity_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='creador_nou',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
