# Generated by Django 5.2.4 on 2025-08-04 17:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_camporeserva_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camporeserva',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
