# Generated by Django 4.2.23 on 2025-10-16 19:39

from django.db import migrations

from django.db import migrations

def forwards(apps, schema_editor):
    Activity = apps.get_model('api', 'Activity')
    UserProfile = apps.get_model('api', 'UserProfile')

    # Asegura que todos los User tengan profile
    # (si ya tienes señal post_save, esto será no-op)
    for up in UserProfile.objects.select_related('user').only('id', 'user_id'):
        pass  # Warm-up

    # Copia FK: creador_user (User) -> creador_profile (UserProfile)
    qs = Activity.objects.all().only('id', 'creador_id')
    for a in qs.iterator():
        user_id = a.creador_id
        if not user_id:
            continue
        up = UserProfile.objects.filter(user_id=user_id).first()
        if up is None:
            # crea si falta (por seguridad)
            up = UserProfile.objects.create(user_id=user_id)
        Activity.objects.filter(pk=a.pk).update(creador_nou_id=up.id)

def backwards(apps, schema_editor):
    Activity = apps.get_model('api', 'Activity')
    UserProfile = apps.get_model('api', 'UserProfile')

    # Volver de profile -> user (por si haces rollback)
    qs = Activity.objects.all().only('id', 'creador_nou_id')
    for a in qs.iterator():
        up_id = a.creador_nou_id
        if not up_id:
            continue
        up = UserProfile.objects.filter(id=up_id).only('user_id').first()
        if up and up.user_id:
            Activity.objects.filter(pk=a.pk).update(creador_id=up.user_id)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_creador_profile'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),  
    ]
