# Generated by Django 5.2.4 on 2025-08-05 14:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_camporeserva_uuid_alter_reserva_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camporeserva',
            options={},
        ),
        migrations.RemoveField(
            model_name='camporeserva',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='camporeserva',
            name='opciones',
        ),
        migrations.RemoveField(
            model_name='camporeserva',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='camporeserva',
            name='promo',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='promo',
        ),
        migrations.AlterField(
            model_name='camporeserva',
            name='tipo',
            field=models.CharField(choices=[('text', 'Texto'), ('email', 'Email'), ('number', 'Número'), ('date', 'Fecha')], max_length=20),
        ),
        migrations.CreateModel(
            name='ReservaForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('max_disponibilidad', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formularios_reserva', to='api.activity')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formularios_reserva', to='api.promo')),
            ],
        ),
        migrations.AddField(
            model_name='camporeserva',
            name='reserva_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='api.reservaform'),
        ),
    ]
