# Generated by Django 4.2.23 on 2025-10-16 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_copy_creador_user_to_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='creador_nou',
        ),
        migrations.AlterField(
            model_name='activity',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to='api.userprofile'),
        ),
    ]
