# Generated by Django 5.2.4 on 2025-08-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_camporeserva_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaform',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='reservaform',
            name='fecha_inicio',
        ),
    ]
