# Generated by Django 5.2.4 on 2025-08-05 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_reservaform_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='reserva_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='api.reservaform'),
        ),
    ]
