# Generated by Django 4.2.23 on 2025-10-16 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_activity_creador_nou_alter_activity_creador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privateplan',
            old_name='creador',
            new_name='creador_user',
        ),
        migrations.RenameField(
            model_name='promo',
            old_name='creador',
            new_name='creador_user',
        ),
        migrations.AddField(
            model_name='privateplan',
            name='creador_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_privateplans', to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='promo',
            name='creador_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_promos', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='privateplan',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='planes_invitados', through='api.PrivatePlanInvitation', to='api.userprofile'),
        ),
    ]
