# Generated by Django 5.2.4 on 2025-08-05 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_reserva_reserva_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camporeserva',
            name='reserva_form',
        ),
        migrations.AddField(
            model_name='reservaform',
            name='campos',
            field=models.ManyToManyField(blank=True, related_name='formularios', to='api.camporeserva'),
        ),
        migrations.AlterField(
            model_name='reservaform',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='reservaform',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='api.promo'),
        ),
    ]
