# Generated by Django 4.2.23 on 2025-10-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_copy_creador_user_to_profile_for_promo_and_privateplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privateplan',
            old_name='creador_profile',
            new_name='creador',
        ),
        migrations.RenameField(
            model_name='promo',
            old_name='creador_profile',
            new_name='creador',
        ),
        migrations.RemoveField(
            model_name='privateplan',
            name='creador_user',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='creador_user',
        ),
    ]
