# Generated by Django 5.2.4 on 2025-08-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_camporeserva_reserva_form_reservaform_campos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='web_link',
        ),
        migrations.AddField(
            model_name='activity',
            name='control_entradas',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
