# Generated by Django 4.2.23 on 2025-10-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_creador_profile_privateplan_creador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='aLaGorra',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
