# Generated by Django 5.2.4 on 2025-08-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_activity_instagram_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='price',
        ),
    ]
