# Generated by Django 4.2.23 on 2025-10-24 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_activity_alagorra'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='recommendedAmount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
