# Generated by Django 5.2.4 on 2025-08-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_reservaform_actividad_alter_reservaform_promo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtemplate',
            name='tipoEvento',
            field=models.IntegerField(choices=[(0, 'Activity'), (1, 'Promo'), (2, 'Plan Privado')], default=0),
        ),
    ]
