# Generated by Django 4.2.23 on 2025-10-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_activity_recommendedamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='recommendedAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
