# Generated by Django 5.2.4 on 2025-08-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_eventtemplate_tipoevento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservaform',
            old_name='actividad',
            new_name='activity',
        ),
    ]
