# Generated by Django 4.2.23 on 2025-10-28 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_activity_recommendedamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='aLaGorra',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_collaborated', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='control_entradas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_events', to='api.place'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='reserva_necesaria',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_tags', to='api.tag'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_collaborated', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_events', to='api.place'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='reserva_necesaria',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_tags', to='api.tag'),
        ),
    ]
