# Generated by Django 5.2.4 on 2025-08-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_actividad_reservaform_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.IntegerField(choices=[(0, 'No asistido'), (1, 'Asistido')], default=0),
        ),
    ]
