# Generated by Django 4.2.23 on 2025-10-29 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0031_alter_activity_alagorra_alter_activity_colaboradores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', 'Contenido inapropiado'), ('duplicate', 'Evento duplicado'), ('spam', 'Spam o publicidad'), ('false_info', 'Información falsa'), ('other', 'Otro')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('solved', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='MessageToUser',
        ),
    ]
