# Generated by Django 4.2.23 on 2025-10-29 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_eventreport_delete_messagetouser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreport',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='eventreport',
            name='object_id',
        ),
        migrations.AddField(
            model_name='eventreport',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.activity'),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.promo'),
        ),
    ]
