# Generated by Django 5.2.4 on 2025-08-12 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_activity_shares_activity_views_promo_shares_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='clicks_on_tickets_link',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
