# Generated by Django 5.2.4 on 2025-08-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_activity_clicks_on_tickets_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaform',
            name='confirmados',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
