# Generated by Django 5.2.4 on 2025-08-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_reservaform_confirmados'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privateplan',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promo',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
