# Generated by Django 5.2.4 on 2025-08-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_activity_active_privateplan_active_promo_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='originLocation',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='originLocationId',
            new_name='locationId',
        ),
    ]
