# Generated by Django 5.2.4 on 2025-08-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_rename_originlocation_userprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
