# Generated by Django 5.2.4 on 2025-08-15 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_userprofile_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
