# Generated by Django 5.2.4 on 2025-08-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_activity_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='free_planes_gratis',
            field=models.IntegerField(default=8),
        ),
    ]
