# Generated by Django 5.2.4 on 2025-08-15 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_userprofile_free_planes_gratis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='free_planes_gratis',
            new_name='available_planes_gratis',
        ),
    ]
