# Generated by Django 5.2.4 on 2025-08-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_paymenteventsbono_alter_paymentforuse_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentEventsBono',
            new_name='PaymentEventsRanges',
        ),
    ]
