# Generated by Django 5.2.4 on 2025-08-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_rename_paymenteventsbono_paymenteventsranges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenteventsranges',
            name='end_range',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
