# Generated by Django 5.2.4 on 2025-08-18 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_paymenteventsranges_end_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment_events_range',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='api.paymenteventsranges'),
        ),
    ]
