# Generated by Django 5.2.4 on 2025-08-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_userprofile_payment_events_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mp_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mp_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mp_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
