# Generated by Django 5.2.4 on 2025-08-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_userprofile_mp_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='creador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pago_suscripcion_mes_actual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pago_suscripcion_mes_proximo',
            field=models.BooleanField(default=False),
        ),
    ]
